### ISSUE TITLE
example data?

### ISSUE THREAD

**Issue by DHekstra** [rs-station/laue-dials#10]
Could you include (a link to) example data needed to run the example script?

**Comment by ianhi** [comment]
A good way to permanently share the data would be via : https://dataverse.harvard.edu/

**Comment by PrinceWalnut** [comment]
@DHekstra the comments at the top of https://github.com/rs-station/laue-dials/blob/main/examples/pipeline.sh include a Zenodo link to DHFR data that can be processed using the example script. Closing with this -- feel free to reopen if this does not answer all concerns
