### ISSUE TITLE
show the user how to set the unit cell dims in the final MTZ 

### ISSUE THREAD

**Issue by DHekstra** [rs-station/laue-dials#50]
since the unit cell dimensions coming out of laue data processing are only loosely tied to reality, perhaps we can add a cell at the end of the tutorial showing the user how to edit the unit cell of the final mtz by hand. something along these lines:

```
import reciprocalspaceship as rs

ds=rs.read_mtz(your.mtz)
ds.cell=(79.4,79.4,37.84,90,90,90)
ds.write_mtz(new_name.mtz)
```

**Comment by PrinceWalnut** [comment]
As of [this commit](https://github.com/rs-station/laue-dials/commit/f8c752d1b222d45104c4bfdcaca375cc13416abd) the user can override the unit cell during `laue.optimize_indexing`. I can certainly add this to the end of the tutorial though.

**Comment by DHekstra** [comment]
Thanks
