### ISSUE TITLE
allow zero macrocycles for laue.optimize_indexing

### ISSUE THREAD

**Issue by kmdalton** [rs-station/laue-dials#67]
Assignment without changing the orientation of the crystal is useful both in practice and diagnostically. We should support `n_macrocycles=0` in `laue.optimize_indexing`

**Comment by kmdalton** [comment]
@PrinceWalnut , i'm assigning you, because i think the relevant change is already in your local branch.

**Comment by PrinceWalnut** [comment]
Should be fixed by commit 43f0706c6308755d51e6d49de3edd85695e8ab8a.

**Comment by kmdalton** [comment]
yay, thanks!
